// Disposable loopback fixtures only; never targets a public service.
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const {pathToFileURL} = require('node:url');
const path = require('node:path');
(async () => {
  const origin = process.env.SWARMMEMO_TEST_URL;
  assert.match(origin || '', /^http:\/\/127\.0\.0\.1:\d+$/);
  const {Client, DelegatedClient, generateKey} = await import(pathToFileURL(path.resolve('clients/javascript/swarmmemo.mjs')));
  const options = {origin, allowInsecureLoopback: true};
  const parent = new Client({...options, key: generateKey()}), requester = new Client({...options, key: generateKey()});
  const childKey = generateKey(), unknownKey = generateKey();
  const send = (client, command) => client.send(client.prepare(command));
  const room = 'grant-ui-' + Date.now();
  await send(parent, {operation: 'room.create', room, visibility: 'public'});
  await send(parent, {operation: 'room.create', room: room + '-private', visibility: 'private'});
  const generation = (await (await fetch(origin + '/api/changes?after=-1')).json()).generation;
  const operations = ['post', 'work.claim'];
  const enrollment = {operation: 'delegation.create', room, ttl: 3600, amount: 100000, data: JSON.stringify({schema: 1, generation, operations, disclosure: 'public'})};
  const ack = await parent.send(parent.prepare(enrollment, {targetKey: childKey}));
  const grantId = ack.data.ack.grant_id;
  await assert.rejects(parent.send(parent.prepare({...enrollment, room: room + '-private'}, {targetKey: unknownKey})));
  const child = new DelegatedClient({...options, key: childKey, grantId, generation, room, operations});
  const posted = await send(child, {operation: 'post', room, visibility: 'public', kind: 'simulation', text: 'Operator-owned disposable worker-key browser fixture. <script>inert</script>'});
  const brief = await send(requester, {operation: 'post', room, kind: 'simulation', text: 'Operator-owned disposable browser request; no external execution.'});
  await send(requester, {operation: 'work.create', message_id: brief.receipt.id, ttl: 3600, data: JSON.stringify({schema: 1, generation, title: 'Disposable delegated attempt', capabilities: []})});
  await send(child, {operation: 'work.claim', message_id: brief.receipt.id, ttl: 60, data: JSON.stringify({schema: 1, generation})});
  const browser = await chromium.launch({headless: true, ...(process.env.CHROMIUM_PATH ? {executablePath: process.env.CHROMIUM_PATH} : {}), args: process.env.PLAYWRIGHT_NO_SANDBOX === 'true' ? ['--no-sandbox'] : []});
  try {
    const context = await browser.newContext({viewport: {width: 320, height: 780}});
    await context.addInitScript(() => Object.defineProperty(navigator, 'clipboard', {value: {writeText: async value => {window.grantCopied = value;}}}));
    const page = await context.newPage(), errors = [], writes = [], streams = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => {const p = new URL(request.url()).pathname; if (!['GET','HEAD','OPTIONS'].includes(request.method()) || /^\/(w|w64|c64)\//.test(p)) writes.push(p); if (/^\/api\/(stream|changes)/.test(p)) streams.push(p);});
    await page.goto(origin + '/delegation/' + grantId);
    assert.match(await page.locator('body').textContent(), /Public grant · active/);
    assert.equal(await page.getByRole('link', {name: 'Public grant JSON'}).count(), 1);
    await page.getByRole('button', {name: 'Copy grant read command', exact: true}).click();
    assert.deepEqual(JSON.parse(await page.evaluate(() => window.grantCopied)), {operation: 'delegation.get', target: grantId});
    await page.getByText('Original signed enrollment proof', {exact: true}).click();
    assert.equal(await page.locator('.grant-record details .copy-button').count(), 0, 'untrusted proofs are not copyable execution examples');
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '320px expanded grant overflow');
    await page.screenshot({path: '/tmp/swarmmemo-worker-grant-mobile.png', fullPage: true});
    const missing = await page.goto(origin + '/delegation/' + unknownKey.fingerprint);
    assert.equal(missing.status(), 404);
    assert.doesNotMatch(await page.locator('body').textContent(), /Original issuer:|Original signed enrollment proof/);
    await page.goto(origin + '/work/' + brief.receipt.id);
    assert.match(await page.locator('body').textContent(), /Worker's parent participant:/);
    assert.equal(await page.getByRole('link', {name: /attempt grant and proof/}).count(), 1);
    assert.equal(await page.getByRole('link', {name: /transition grant and proof/}).count(), 1);
    assert.equal(await page.locator('a[href="/agent/' + grantId + '"]').count(), 0);
    assert.deepEqual(streams, [], 'grant/work pages must not subscribe');
    await page.goto(origin + '/r/' + room);
    const memo = page.locator('#e-' + posted.receipt.id);
    assert.equal(await memo.getByRole('link', {name: /Worker key .* public grant and proof/}).count(), 1);
    const live = await send(child, {operation: 'post', room, visibility: 'public', kind: 'simulation', text: 'Operator-owned live-render regression fixture.'});
    await page.locator('.new-messages').waitFor({state: 'visible'});
    await page.locator('.new-messages').click();
    assert.equal(await page.locator('#e-' + live.receipt.id).getByRole('link', {name: /Worker key .* public grant and proof/}).count(), 1);
    assert.equal(await page.locator('a[href="/agent/' + grantId + '"]').count(), 0);
    assert.deepEqual(writes, []); assert.deepEqual(errors, []);
    const plain = await browser.newContext({javaScriptEnabled: false, viewport: {width: 320, height: 780}});
    const plainPage = await plain.newPage();
    await plainPage.goto(origin + '/delegation/' + grantId);
    assert.match(await plainPage.locator('body').textContent(), /delegation.get/);
    await plainPage.getByText('Original signed enrollment proof', {exact: true}).click();
    assert.ok(await plainPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '320px no-JS grant overflow');
    await plainPage.goto(origin + '/e/' + posted.receipt.id);
    assert.equal(await plainPage.getByRole('link', {name: /Worker key .* public grant and proof/}).count(), 1);
    await plain.close(); await context.close();
    console.log('PASS: actual delegated enrollment, private rejection, public proof/no-JS/mobile, work child-parent attribution, live parity, no browser writes or grant polling.');
  } finally { await browser.close(); }
})().catch(error => {console.error(error); process.exitCode = 1;});
