// Isolated local-server browser regression. Same environment as browser_test.cjs.
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true, ...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {}), args:process.env.PLAYWRIGHT_NO_SANDBOX === 'true' ? ['--no-sandbox'] : []});
  const origin = process.env.SWARMMEMO_TEST_URL || 'http://127.0.0.1:8089';
  const context = await browser.newContext({viewport:{width:1280,height:1000}});
  await context.addInitScript(() => {
    window.copiedTexts = [];
    Object.defineProperty(navigator, 'clipboard', {configurable:true, value:{writeText:async text => {window.copiedTexts.push(text);}}});
  });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  let writes = 0;
  page.on('request', request => {if (/\/(w|w64|c64)\//.test(new URL(request.url()).pathname) || request.method() === 'POST') writes++;});
  try {
    await page.goto(origin);
    const copyURL=page.getByRole('button', {name:'Copy agent entry URL', exact:true});
    assert.equal(await copyURL.locator('svg').getAttribute('aria-hidden'),'true');
    assert.equal(await copyURL.locator('svg').getAttribute('focusable'),'false');
    const copyPath=await copyURL.locator('svg path').getAttribute('d');
    await copyURL.click();
    assert.equal(await copyURL.locator('span').textContent(),'Copied');
    assert.notEqual(await copyURL.locator('svg path').getAttribute('d'),copyPath,'success uses a check icon');
    assert.equal(await copyURL.getAttribute('aria-label'),'Copy agent entry URL','action stays explicitly named for assistive technology');
    assert.equal(await page.evaluate(() => window.copiedTexts.at(-1)), 'https://swarmmemo.com/llms.txt');
    assert.equal(writes, 0, 'copying an agent entry URL must not fetch or post it');
    await page.goto(origin + '/docs');
    const code = await page.locator('.prose pre code').first().textContent();
    await page.getByRole('button', {name:'Copy', exact:true}).first().focus();
    await page.keyboard.press('Enter');
    await page.waitForFunction(() => window.copiedTexts.length > 0);
    assert.equal(await page.evaluate(() => window.copiedTexts.at(-1)), code.trim());
    assert.equal(writes, 0);
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'copy controls cause mobile overflow');
    await page.evaluate(() => {navigator.clipboard.writeText = async () => {throw Error('denied');}; document.execCommand = () => false;});
    await page.getByRole('button', {name:'Copy', exact:true}).first().click();
    await page.getByRole('textbox', {name:'Text to copy manually'}).waitFor();
    assert.equal(await page.getByRole('textbox', {name:'Text to copy manually'}).inputValue(), code.trim());
    assert.match(await page.locator('#toast').textContent(), /copy it manually/);
    const disclosure = 'Imported / populated — curator summary, not an original SwarmMemo post.\n';
    const marker = 'Polish summary ' + Date.now();
    // The imported kind is reserved: an anonymous poster must not be able to buy
    // the curator badge, and a genuine curated import must still render as one.
    const anonymous = await context.request.post(origin + '/v1/command', {data:{operation:'post',kind:'imported',text:disclosure + marker + ' forged',room:'polish-test',page:'main'}});
    assert.equal(anonymous.status(), 403);
    assert.equal((await anonymous.json()).error.code, 'reserved_kind');
    const sendAsCurator = await require('./home_density_test.cjs').curator(origin);
    const receipt = (await sendAsCurator({operation:'post',kind:'imported',text:disclosure + marker,room:'polish-test',page:'main'})).receipt;
    await page.setViewportSize({width:1280,height:1000});
    await page.goto(origin + '/r/polish-test');
    assert.equal(await page.locator('#e-' + receipt.id + ' .memo-text').textContent(), marker);
    assert.equal(await page.locator('#e-' + receipt.id + ' .kind').textContent(), '');
    assert.match(await page.locator('#e-' + receipt.id + ' .kind').getAttribute('aria-label'), /^Imported summary — curator summary/);
    const api = await context.request.get(origin + '/e/' + receipt.id + '?format=json');
    assert.equal((await api.json()).messages[0].text, disclosure + marker, 'stored/API provenance was rewritten');
    const liveID = (await sendAsCurator({operation:'post',kind:'imported',text:disclosure + marker + ' live',room:'polish-test',page:'main'})).receipt.id;
    await page.locator('.new-messages').waitFor({state:'visible'});
    await page.locator('.new-messages').click();
    assert.equal(await page.locator('#e-' + liveID + ' .memo-text').textContent(), marker + ' live');
    assert.equal(await page.locator('#e-' + liveID + ' .kind').textContent(), '');
    assert.match(await page.locator('#e-' + liveID + ' .kind').getAttribute('aria-label'), /^Imported summary — curator summary/);
    assert.equal(await page.locator('#compose').evaluate(e=>e.open),true,'composer is open at rest');
    await page.locator('#memo-text').fill('Receipt polish');
    await page.locator('#compose-form button[type=submit]').click();
    // Remembered posts also offer a backup link; select the receipt by its name.
    await page.getByRole('link',{name:'Open message →',exact:true}).waitFor();
    const memoPath = await page.getByRole('link',{name:'Open message →',exact:true}).getAttribute('href');
    await page.getByRole('button', {name:'Copy link',exact:true}).click();
    assert.equal(await page.evaluate(() => window.copiedTexts.at(-1)), origin + memoPath);
    const writesBeforeHandoff = writes;
    const guide = await page.goto(origin + '/for-agents');
    assert.match(guide.headers().link, /llms.txt/);
    await page.getByRole('button', {name:'Copy handoff',exact:true}).click();
    const handoff = await page.evaluate(() => window.copiedTexts.at(-1));
    assert.match(handoff, /https:\/\/swarmmemo.com\/llms.txt/);
    assert.match(handoff, /never upload a private key/);
    assert.equal(await page.locator('head link[rel="service-desc"]').getAttribute('href'), '/openapi.json');
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'agent guide causes mobile overflow');
    assert.equal(await page.locator('#optional-tools').count(), 0, 'the agent handoff is one screen');
    // The optional-tool reference now lives on /docs, one link away.
    await page.goto(origin + '/docs');
    assert.equal(await page.locator('#optional-tools').evaluate(el => el.open), false, 'advanced tools start collapsed');
    assert.equal(await page.locator('#signed-commands h3').isVisible(), false);
    await page.locator('#optional-tools > summary').focus();
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('#signed-commands h3').isVisible(), true, 'keyboard opens native optional tools');
    await page.goto(origin + '/docs#signed-commands');
    assert.equal(await page.locator('#signed-commands h3').isVisible(), true, 'existing deep links reveal optional tools');
    const workspace = await page.goto(origin + '/me');
    assert.equal(workspace.headers()['x-robots-tag'], 'noindex, follow');
    assert.match(await page.locator('.workspace-onboarding').textContent(), /This browser is optional/);
    assert.equal(writes, writesBeforeHandoff, 'agent handoff must not post or execute examples');
    const plain = await browser.newContext({javaScriptEnabled:false});
    const plainPage = await plain.newPage(); await plainPage.goto(origin + '/for-agents');
    assert.match(await plainPage.locator('.agent-handoff code').textContent(), /llms.txt/);
    assert.equal(await plainPage.getByRole('button', {name:'Copy handoff',exact:true}).count(), 0);
    await plainPage.goto(origin + '/docs');
    assert.equal(await plainPage.locator('#optional-tools').evaluate(el => el.open), false);
    await plainPage.locator('#optional-tools > summary').click();
    assert.equal(await plainPage.locator('#signed-commands h3').isVisible(), true, 'optional tools work without JavaScript');
    await plainPage.goto(origin + '/docs#signed-commands');
    assert.equal(await plainPage.locator('#signed-commands h3').isVisible(), true, 'no-JS deep links reveal optional tools');
    await plain.close();
    assert.deepEqual(errors, []);
    console.log('PASS: inert copy URL; keyboard code copy; blocked clipboard fallback; mobile width; compact import tag; original API provenance; receipt permalink/copy; agent handoff/meta/headers; browser-optional workspace; no-JS guide.');
  } finally {await browser.close();}
})().catch(error => {console.error(error);process.exitCode = 1;});
