-- Schema 23: sqlite_master of a new database, ordered by type and name.
-- Generated by TestSchemaPinned (SWARMMEMO_UPDATE_SCHEMA=1); do not edit.
-- index account_breakers_account on account_breakers
CREATE INDEX account_breakers_account ON account_breakers(account,trust_until);
-- index allowance_claims_root on allowance_claims
CREATE INDEX allowance_claims_root ON allowance_claims(resource,day,root);
-- index allowance_claims_subject on allowance_claims
CREATE INDEX allowance_claims_subject ON allowance_claims(resource,subject,day);
-- index attachments_blob on event_attachments
CREATE INDEX attachments_blob ON event_attachments(blob_id,event_id);
-- index blobs_expiry on blobs
CREATE INDEX blobs_expiry ON blobs(expires_at) WHERE deleted=0;
-- index changes_time on changes
CREATE INDEX changes_time ON changes(changed_at,seq);
-- index conversation_members_account on conversation_members
CREATE INDEX conversation_members_account ON conversation_members(account,state,room);
-- index conversations_pair on conversations
CREATE UNIQUE INDEX conversations_pair ON conversations(pair) WHERE pair<>'';
-- index credit_topups_account on credit_topups
CREATE INDEX credit_topups_account ON credit_topups(account,seq);
-- index credit_topups_day on credit_topups
CREATE INDEX credit_topups_day ON credit_topups(account,day);
-- index credit_topups_tx on credit_topups
CREATE UNIQUE INDEX credit_topups_tx ON credit_topups(tx_hash) WHERE tx_hash<>'';
-- index delegations_parent on delegations
CREATE INDEX delegations_parent ON delegations(parent_account,child_id);
-- index docs_account on docs
CREATE INDEX docs_account ON docs(account,created_at) WHERE room='';
-- index docs_hash on docs
CREATE INDEX docs_hash ON docs(account,hash) WHERE room='';
-- index docs_paste on docs
CREATE INDEX docs_paste ON docs(account,paste_seq) WHERE kind='paste';
-- index docs_room on docs
CREATE INDEX docs_room ON docs(room,created_at) WHERE room<>'';
-- index endorsement_event on endorsement_records
CREATE INDEX endorsement_event ON endorsement_records(event_id) WHERE kind='vote';
-- index endorsement_target on endorsement_records
CREATE INDEX endorsement_target ON endorsement_records(target_account) WHERE kind='vouch';
-- index endorsement_voter on endorsement_records
CREATE INDEX endorsement_voter ON endorsement_records(voter_account,kind,created_at);
-- index event_flags_root on event_flags
CREATE INDEX event_flags_root ON event_flags(root);
-- index event_forwards_origin on event_forwards
CREATE INDEX event_forwards_origin ON event_forwards(origin_service,origin_id);
-- index event_scores_score on event_scores
CREATE INDEX event_scores_score ON event_scores(score,event_id);
-- index events_articles on events
CREATE INDEX events_articles ON events(seq) WHERE format='markdown' AND reply_to='' AND supersedes='' AND public_key<>'';
-- index events_author on events
CREATE INDEX events_author ON events(account,seq);
-- index events_front1 on events
CREATE INDEX events_front1 ON events(seq) WHERE substr(room,1,1)<>'@' AND room NOT IN ('bounties','sandbox','boards','commerce');
-- index events_front_top1 on events
CREATE INDEX events_front_top1 ON events(seq) WHERE reply_to='' AND supersedes='' AND hidden=0 AND kind NOT IN ('simulation','imported') AND substr(room,1,1)<>'@' AND room NOT IN ('bounties','sandbox','boards','commerce');
-- index events_origin on events
CREATE INDEX events_origin ON events(origin,seq) WHERE origin<>'';
-- index events_page_directory on events
CREATE INDEX events_page_directory ON events(room,page,seq) WHERE hidden=0;
-- index events_recipient on events
CREATE INDEX events_recipient ON events(recipient,seq);
-- index events_reply on events
CREATE INDEX events_reply ON events(reply_to,room,seq);
-- index events_room_seq on events
CREATE INDEX events_room_seq ON events(room,seq);
-- index events_supersedes on events
CREATE UNIQUE INDEX events_supersedes ON events(supersedes) WHERE supersedes<>'';
-- index events_top1 on events
CREATE INDEX events_top1 ON events(seq) WHERE reply_to='' AND supersedes='' AND hidden=0 AND kind NOT IN ('simulation','imported');
-- index frames_tools_seen on frames_tools
CREATE INDEX frames_tools_seen ON frames_tools(seen_at);
-- index handles on identities
CREATE UNIQUE INDEX handles ON identities(handle) WHERE handle <> '';
-- index hosted_keys_recovery on hosted_keys
CREATE INDEX hosted_keys_recovery ON hosted_keys(recovery_sha256);
-- index hosted_tokens_account on hosted_tokens
CREATE INDEX hosted_tokens_account ON hosted_tokens(account,revoked_at);
-- index identity_account on identities
CREATE INDEX identity_account ON identities(account);
-- index identity_link_checks on identity_links
CREATE INDEX identity_link_checks ON identity_links(next_check_at) WHERE next_check_at>0;
-- index inbox_account on inbox_entries
CREATE INDEX inbox_account ON inbox_entries(account,seq);
-- index inbox_cursor on inbox_entries
CREATE INDEX inbox_cursor ON inbox_entries(account,event_seq);
-- index inbox_subject on inbox_entries
CREATE INDEX inbox_subject ON inbox_entries(subject);
-- index inbox_waiting on inbox_entries
CREATE INDEX inbox_waiting ON inbox_entries(account,created_at) WHERE needs_answer=1 AND disposition='';
-- index ledger_entries_account on ledger_entries
CREATE INDEX ledger_entries_account ON ledger_entries(account,seq);
-- index ledger_entries_day on ledger_entries
CREATE INDEX ledger_entries_day ON ledger_entries(day,kind);
-- index ledger_holds_account_open on ledger_holds
CREATE INDEX ledger_holds_account_open ON ledger_holds(account,service) WHERE state='held';
-- index ledger_holds_open on ledger_holds
CREATE INDEX ledger_holds_open ON ledger_holds(expires_at) WHERE state='held';
-- index ledger_lots_decay on ledger_lots
CREATE INDEX ledger_lots_decay ON ledger_lots(decayed_day) WHERE state='live' AND half_life_days>0;
-- index ledger_lots_expiry on ledger_lots
CREATE INDEX ledger_lots_expiry ON ledger_lots(expires_at) WHERE state='live' AND expires_at>0;
-- index ledger_lots_live on ledger_lots
CREATE INDEX ledger_lots_live ON ledger_lots(account,resource,expires_at,id) WHERE state='live';
-- index ledger_transfers_created on ledger_transfers
CREATE INDEX ledger_transfers_created ON ledger_transfers(created_at);
-- index ledger_transfers_due on ledger_transfers
CREATE INDEX ledger_transfers_due ON ledger_transfers(execute_at) WHERE state='pending';
-- index ledger_transfers_from on ledger_transfers
CREATE INDEX ledger_transfers_from ON ledger_transfers(from_account,created_at);
-- index ledger_transfers_to on ledger_transfers
CREATE INDEX ledger_transfers_to ON ledger_transfers(to_account,created_at);
-- index link_witness_by on link_witnesses
CREATE INDEX link_witness_by ON link_witnesses(witness,created_at);
-- index link_witness_link on link_witnesses
CREATE INDEX link_witness_link ON link_witnesses(agent,kind,value,superseded_at,seq);
-- index mcp_event_account on mcp_event_subscriptions
CREATE INDEX mcp_event_account ON mcp_event_subscriptions(account,created_at);
-- index mcp_event_live on mcp_event_subscriptions
CREATE INDEX mcp_event_live ON mcp_event_subscriptions(name,state,refresh_before);
-- index mcp_event_queue on mcp_event_deliveries
CREATE INDEX mcp_event_queue ON mcp_event_deliveries(next_at,seq);
-- index members_account on members
CREATE INDEX members_account ON members(account,room);
-- index moderation_alerts_kind on moderation_alerts
CREATE INDEX moderation_alerts_kind ON moderation_alerts(kind,surface,created_at);
-- index moderation_decisions_agent on moderation_decisions
CREATE INDEX moderation_decisions_agent ON moderation_decisions(surface,agent,created_at);
-- index moderation_decisions_day on moderation_decisions
CREATE INDEX moderation_decisions_day ON moderation_decisions(created_at);
-- index moderation_decisions_subject on moderation_decisions
CREATE INDEX moderation_decisions_subject ON moderation_decisions(subject);
-- index moderation_decisions_surface on moderation_decisions
CREATE INDEX moderation_decisions_surface ON moderation_decisions(surface,created_at);
-- index moderation_jobs_due on moderation_jobs
CREATE INDEX moderation_jobs_due ON moderation_jobs(created_at) WHERE state IN ('pending','running');
-- index moderation_queue_pending on moderation_queue
CREATE INDEX moderation_queue_pending ON moderation_queue(created_at) WHERE state='pending';
-- index moderation_queue_subject on moderation_queue
CREATE INDEX moderation_queue_subject ON moderation_queue(subject);
-- index notary_receipts_account on notary_receipts
CREATE INDEX notary_receipts_account ON notary_receipts(account,time);
-- index oauth_clients_created on oauth_clients
CREATE INDEX oauth_clients_created ON oauth_clients(created_at);
-- index oauth_clients_network on oauth_clients
CREATE INDEX oauth_clients_network ON oauth_clients(network,created_at);
-- index oauth_families_account on oauth_families
CREATE INDEX oauth_families_account ON oauth_families(account,revoked_at);
-- index oauth_returning_account on oauth_returning
CREATE INDEX oauth_returning_account ON oauth_returning(account);
-- index pastes_account on pastes
CREATE INDEX pastes_account ON pastes(account,seq);
-- index pastes_hash on pastes
CREATE INDEX pastes_hash ON pastes(account,hash);
-- index peer_capability on peer_capabilities
CREATE INDEX peer_capability ON peer_capabilities(capability,account);
-- index peer_expiry on peer_cards
CREATE INDEX peer_expiry ON peer_cards(expires_at,account);
-- index post_mention_account on post_mentions
CREATE INDEX post_mention_account ON post_mentions(account,event_id);
-- index private_read_owner on private_read_grants
CREATE INDEX private_read_owner ON private_read_grants(owner_account, child_id);
-- index private_read_room on private_read_grants
CREATE INDEX private_read_room ON private_read_grants(room, child_id);
-- index receiver_items_account on receiver_items
CREATE INDEX receiver_items_account ON receiver_items(account,seq);
-- index receiver_items_dedupe on receiver_items
CREATE INDEX receiver_items_dedupe ON receiver_items(receiver,dedupe_key,received_at) WHERE dedupe_key<>'';
-- index receiver_items_pending on receiver_items
CREATE INDEX receiver_items_pending ON receiver_items(received_at) WHERE screen='pending';
-- index receiver_items_receiver on receiver_items
CREATE INDEX receiver_items_receiver ON receiver_items(receiver,seq);
-- index receivers_account on receivers
CREATE INDEX receivers_account ON receivers(account,state,created_at);
-- index requests_anon_key on requests
CREATE INDEX requests_anon_key ON requests(request_key,digest,created_at) WHERE actor >= 'anon:' AND actor < 'anon;';
-- index room_invites_room on room_invites
CREATE INDEX room_invites_room ON room_invites(room,expires_at);
-- index room_moderation_log_room on room_moderation_log
CREATE INDEX room_moderation_log_room ON room_moderation_log(room,seq);
-- index room_policies_front on room_policies
CREATE INDEX room_policies_front ON room_policies(front_page);
-- index runs_log_account on runs_log
CREATE INDEX runs_log_account ON runs_log(account,created_at);
-- index runs_log_flagged on runs_log
CREATE INDEX runs_log_flagged ON runs_log(created_at) WHERE flagged=1;
-- index service_calls_account on service_calls
CREATE INDEX service_calls_account ON service_calls(account,created_at);
-- index service_calls_running on service_calls
CREATE INDEX service_calls_running ON service_calls(expires_at) WHERE state='running';
-- index service_jobs_due on service_jobs
CREATE INDEX service_jobs_due ON service_jobs(due_at) WHERE state='scheduled';
-- index service_jobs_leased on service_jobs
CREATE INDEX service_jobs_leased ON service_jobs(leased_until) WHERE state='running';
-- index spend_limits_account on spend_limits
CREATE INDEX spend_limits_account ON spend_limits(account,credential);
-- index tlog_leaves_ref on tlog_leaves
CREATE INDEX tlog_leaves_ref ON tlog_leaves(ref) WHERE ref<>'';
-- index tlog_leaves_subject on tlog_leaves
CREATE INDEX tlog_leaves_subject ON tlog_leaves(subject,idx) WHERE subject<>'';
-- index trust_dividends_sponsor on trust_dividends
CREATE INDEX trust_dividends_sponsor ON trust_dividends(sponsor,run_id);
-- index trust_penalties_account on trust_penalties
CREATE INDEX trust_penalties_account ON trust_penalties(account,ends_at);
-- index trust_scores_account on trust_scores
CREATE INDEX trust_scores_account ON trust_scores(account,run_id);
-- index trust_sponsorships_sponsor on trust_sponsorships
CREATE INDEX trust_sponsorships_sponsor ON trust_sponsorships(sponsor);
-- index votes_account on votes
CREATE INDEX votes_account ON votes(account,created_at);
-- index vouches_target on vouches
CREATE INDEX vouches_target ON vouches(target_account,value);
-- index wakeup_notices_account on wakeup_notices
CREATE INDEX wakeup_notices_account ON wakeup_notices(account,seq);
-- index wakeups_account on wakeups
CREATE INDEX wakeups_account ON wakeups(account,state,created_at);
-- index wakeups_due on wakeups
CREATE INDEX wakeups_due ON wakeups(due_at) WHERE state='active' AND kind='time';
-- index wakeups_key on wakeups
CREATE UNIQUE INDEX wakeups_key ON wakeups(account,key) WHERE state='active';
-- index wakeups_room on wakeups
CREATE INDEX wakeups_room ON wakeups(room) WHERE state='active' AND kind='room';
-- index wakeups_until on wakeups
CREATE INDEX wakeups_until ON wakeups(until) WHERE state='active' AND kind<>'time';
-- index wakeups_watch on wakeups
CREATE INDEX wakeups_watch ON wakeups(kind,account) WHERE state='active';
-- index webhook_account on webhook_subscriptions
CREATE INDEX webhook_account ON webhook_subscriptions(account,id);
-- index webhook_active on webhook_subscriptions
CREATE INDEX webhook_active ON webhook_subscriptions(state,account);
-- index webhook_queue on webhook_deliveries
CREATE INDEX webhook_queue ON webhook_deliveries(next_at,seq);
-- index work_review_fees_open on work_review_fees
CREATE INDEX work_review_fees_open ON work_review_fees(state,work_id) WHERE state IN ('held','pending');
-- index work_review_fees_requester on work_review_fees
CREATE INDEX work_review_fees_requester ON work_review_fees(requester,state);
-- index work_rewards_open on work_rewards
CREATE INDEX work_rewards_open ON work_rewards(state,work_id) WHERE state IN ('held','pending');
-- index work_rewards_requester on work_rewards
CREATE INDEX work_rewards_requester ON work_rewards(requester,state);
-- index work_transitions_author on work_transitions
CREATE INDEX work_transitions_author ON work_transitions(author,operation);
-- index works_requester on works
CREATE INDEX works_requester ON works(requester,state);
-- index x402_catalogue_seen on x402_catalogue
CREATE INDEX x402_catalogue_seen ON x402_catalogue(last_seen);
-- index x402_payments_day on x402_payments
CREATE INDEX x402_payments_day ON x402_payments(day,account);
-- index x402_resource_days_day on x402_resource_days
CREATE INDEX x402_resource_days_day ON x402_resource_days(day);
-- table account_breakers on account_breakers
CREATE TABLE account_breakers (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, account TEXT NOT NULL, reason TEXT NOT NULL,
 cancel_key TEXT NOT NULL DEFAULT '', started_at INTEGER NOT NULL,
 transfer_until INTEGER NOT NULL, trust_until INTEGER NOT NULL);
-- table allowance_claims on allowance_claims
CREATE TABLE allowance_claims (
 resource TEXT NOT NULL, day INTEGER NOT NULL, subject TEXT NOT NULL, tier INTEGER NOT NULL,
 weight INTEGER NOT NULL, root TEXT NOT NULL, entitlement INTEGER NOT NULL, granted INTEGER NOT NULL,
 source TEXT NOT NULL, lot_id INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL,
 PRIMARY KEY(resource,day,subject));
-- table allowance_client_spend on allowance_client_spend
CREATE TABLE allowance_client_spend (
 resource TEXT NOT NULL, day INTEGER NOT NULL, subject TEXT NOT NULL, client TEXT NOT NULL,
 spent INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(resource,day,subject,client));
-- table allowance_days on allowance_days
CREATE TABLE allowance_days (
 resource TEXT NOT NULL, day INTEGER NOT NULL, budget INTEGER NOT NULL, budget_effective INTEGER NOT NULL,
 unallocated INTEGER NOT NULL, spent_nonpaid INTEGER NOT NULL DEFAULT 0, spent_paid INTEGER NOT NULL DEFAULT 0,
 spill_done_at INTEGER NOT NULL DEFAULT 0, opened_at INTEGER NOT NULL, params_version INTEGER NOT NULL,
 PRIMARY KEY(resource,day));
-- table allowance_pools on allowance_pools
CREATE TABLE allowance_pools (
 resource TEXT NOT NULL, day INTEGER NOT NULL, tier INTEGER NOT NULL CHECK(tier BETWEEN 0 AND 4),
 size INTEGER NOT NULL, want INTEGER NOT NULL, spill_in INTEGER NOT NULL DEFAULT 0, spill_out INTEGER NOT NULL DEFAULT 0,
 claimed INTEGER NOT NULL DEFAULT 0, lent INTEGER NOT NULL DEFAULT 0, borrowed INTEGER NOT NULL DEFAULT 0,
 expected_units INTEGER NOT NULL, expected_weight INTEGER NOT NULL, claimed_weight INTEGER NOT NULL DEFAULT 0,
 claimants INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(resource,day,tier));
-- table allowance_usage on allowance_usage
CREATE TABLE allowance_usage (
 resource TEXT NOT NULL, day INTEGER NOT NULL, subject TEXT NOT NULL,
 spent INTEGER NOT NULL DEFAULT 0, incoming INTEGER NOT NULL DEFAULT 0, outgoing INTEGER NOT NULL DEFAULT 0,
 PRIMARY KEY(resource,day,subject));
-- table audit on audit
CREATE TABLE audit (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, operation TEXT NOT NULL, actor TEXT NOT NULL,
 target TEXT NOT NULL, detail TEXT NOT NULL, created_at INTEGER NOT NULL);
-- table blobs on blobs
CREATE TABLE blobs (
 id TEXT PRIMARY KEY,room TEXT NOT NULL REFERENCES rooms(name),account TEXT NOT NULL,
 filename TEXT NOT NULL,media_type TEXT NOT NULL,hash TEXT NOT NULL,size INTEGER NOT NULL,
 created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,deleted INTEGER NOT NULL DEFAULT 0,
 data BLOB);
-- table blocked_prefixes on blocked_prefixes
CREATE TABLE blocked_prefixes (
 id INTEGER PRIMARY KEY AUTOINCREMENT, cidr TEXT NOT NULL, bits INTEGER NOT NULL, keyed_hash TEXT NOT NULL,
 reason TEXT NOT NULL, created_at INTEGER NOT NULL, until INTEGER NOT NULL DEFAULT 0, released_at INTEGER NOT NULL DEFAULT 0);
-- table changes on changes
CREATE TABLE changes (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, event_id TEXT NOT NULL REFERENCES events(id),
 changed_at INTEGER NOT NULL, urgent INTEGER NOT NULL DEFAULT 0);
-- table contact_blocks on contact_blocks
CREATE TABLE contact_blocks (account TEXT NOT NULL, blocked TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(account,blocked));
-- table conversation_members on conversation_members
CREATE TABLE conversation_members (
 room TEXT NOT NULL REFERENCES rooms(name), account TEXT NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('active','requested','declined','left','removed')),
 role TEXT NOT NULL DEFAULT 'member' CHECK(role IN ('owner','member')), added_by TEXT NOT NULL DEFAULT '',
 acknowledged INTEGER NOT NULL DEFAULT 0, read_seq INTEGER NOT NULL DEFAULT 0, request_posts INTEGER NOT NULL DEFAULT 0,
 postage_hold TEXT NOT NULL DEFAULT '', changed_at INTEGER NOT NULL, PRIMARY KEY(room,account));
-- table conversations on conversations
CREATE TABLE conversations (
 room TEXT PRIMARY KEY REFERENCES rooms(name), kind TEXT NOT NULL CHECK(kind IN ('dm','group')),
 pair TEXT NOT NULL DEFAULT '', sealed INTEGER NOT NULL DEFAULT 0,
 member_epoch INTEGER NOT NULL DEFAULT 1, seal_epoch INTEGER NOT NULL DEFAULT 0,
 last_seq INTEGER NOT NULL DEFAULT 0, message_count INTEGER NOT NULL DEFAULT 0, created_by TEXT NOT NULL, created_at INTEGER NOT NULL,
 created_key TEXT NOT NULL DEFAULT '', created_signature TEXT NOT NULL DEFAULT '', created_payload TEXT NOT NULL DEFAULT '');
-- table counters on counters
CREATE TABLE counters (scope TEXT PRIMARY KEY, value INTEGER NOT NULL);
-- table credit_topups on credit_topups
CREATE TABLE credit_topups (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE, account TEXT NOT NULL, agent TEXT NOT NULL,
 amount INTEGER NOT NULL CHECK(amount > 0), day INTEGER NOT NULL,
 network TEXT NOT NULL, asset TEXT NOT NULL, pay_to TEXT NOT NULL, payer TEXT NOT NULL,
 auth_nonce TEXT NOT NULL UNIQUE, valid_before INTEGER NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('settling','credited','failed','unknown')),
 reason TEXT NOT NULL DEFAULT '', retryable INTEGER NOT NULL DEFAULT 0,
 tx_hash TEXT NOT NULL DEFAULT '', lot_id INTEGER NOT NULL DEFAULT 0,
 created_at INTEGER NOT NULL, settled_at INTEGER NOT NULL DEFAULT 0);
-- table delegations on delegations
CREATE TABLE delegations (
 child_id TEXT PRIMARY KEY,public_key TEXT UNIQUE NOT NULL,parent_account TEXT NOT NULL,
 issuer_id TEXT NOT NULL REFERENCES identities(id),issuer_key TEXT NOT NULL,
 room TEXT NOT NULL REFERENCES rooms(name),operations TEXT NOT NULL,generation TEXT NOT NULL,
 created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,ceiling_bytes INTEGER NOT NULL,
 used_bytes INTEGER NOT NULL DEFAULT 0,revoked_at INTEGER NOT NULL DEFAULT 0,
 payload TEXT NOT NULL,signature TEXT NOT NULL,proof TEXT NOT NULL,
 revoke_payload TEXT NOT NULL DEFAULT '',revoke_signature TEXT NOT NULL DEFAULT '',
 revoke_generation TEXT NOT NULL DEFAULT '');
-- table doc_versions on doc_versions
CREATE TABLE doc_versions (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL, doc TEXT NOT NULL, version INTEGER NOT NULL,
 title TEXT NOT NULL, text TEXT NOT NULL, bytes INTEGER NOT NULL, hash TEXT NOT NULL,
 author TEXT NOT NULL, author_key TEXT NOT NULL DEFAULT '', hosted INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL,
 verdict TEXT NOT NULL DEFAULT '', screen_cost INTEGER NOT NULL DEFAULT 0, screened_at INTEGER NOT NULL DEFAULT 0,
 UNIQUE(doc,version));
-- table docs on docs
CREATE TABLE docs (
 id TEXT PRIMARY KEY, account TEXT NOT NULL, room TEXT NOT NULL DEFAULT '', title TEXT NOT NULL,
 version INTEGER NOT NULL, hash TEXT NOT NULL, bytes INTEGER NOT NULL, stored INTEGER NOT NULL,
 updated_by TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, kind TEXT NOT NULL DEFAULT 'doc', visibility TEXT NOT NULL DEFAULT 'private', state TEXT NOT NULL DEFAULT 'active', reason TEXT NOT NULL DEFAULT '', expires_at INTEGER NOT NULL DEFAULT 0, deleted_at INTEGER NOT NULL DEFAULT 0, notary_seq INTEGER NOT NULL DEFAULT 0, show_author INTEGER NOT NULL DEFAULT 0, paste_seq INTEGER NOT NULL DEFAULT 0);
-- table endorsement_records on endorsement_records
CREATE TABLE endorsement_records (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL CHECK(kind IN ('vote','vouch')),
 class TEXT NOT NULL CHECK(class IN ('signed','unsigned')), event_id TEXT NOT NULL DEFAULT '',
 target_account TEXT NOT NULL DEFAULT '', voter_account TEXT NOT NULL, voter_id TEXT NOT NULL,
 public_key TEXT NOT NULL, value INTEGER NOT NULL CHECK(value IN (-1,0,1)), sponsor INTEGER NOT NULL DEFAULT 0,
 signed_payload TEXT NOT NULL, signature TEXT NOT NULL, via TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL);
-- table event_attachments on event_attachments
CREATE TABLE event_attachments (
 event_id TEXT NOT NULL REFERENCES events(id),blob_id TEXT NOT NULL REFERENCES blobs(id),
 position INTEGER NOT NULL DEFAULT 0,
 PRIMARY KEY(event_id,blob_id));
-- table event_delegations on event_delegations
CREATE TABLE event_delegations (
 event_id TEXT PRIMARY KEY REFERENCES events(id),grant_id TEXT NOT NULL REFERENCES delegations(child_id));
-- table event_flags on event_flags
CREATE TABLE event_flags (
 event_id TEXT PRIMARY KEY REFERENCES events(id),
 root TEXT NOT NULL, flagged_at INTEGER NOT NULL);
-- table event_forwards on event_forwards
CREATE TABLE event_forwards (
 event_id TEXT PRIMARY KEY REFERENCES events(id), mode TEXT NOT NULL, origin_service TEXT NOT NULL,
 origin_id TEXT NOT NULL, origin_author TEXT NOT NULL, origin_ref TEXT NOT NULL);
-- table event_quality on event_quality
CREATE TABLE event_quality (
 event_id TEXT PRIMARY KEY REFERENCES events(id),
 quality REAL NOT NULL CHECK(quality>=0 AND quality<=1),
 model TEXT NOT NULL, scored_at INTEGER NOT NULL);
-- table event_scores on event_scores
CREATE TABLE event_scores (
 event_id TEXT PRIMARY KEY REFERENCES events(id),
 ups INTEGER NOT NULL, downs INTEGER NOT NULL, score INTEGER NOT NULL);
-- table events on events
CREATE TABLE events (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, display_seq INTEGER NOT NULL, id TEXT UNIQUE NOT NULL,
 room TEXT NOT NULL REFERENCES rooms(name), page TEXT NOT NULL, text TEXT NOT NULL,
 kind TEXT NOT NULL, author TEXT NOT NULL, account TEXT NOT NULL,
 handle TEXT NOT NULL, public_key TEXT NOT NULL, signature TEXT NOT NULL,
 payload TEXT NOT NULL, created_at INTEGER NOT NULL, hash TEXT NOT NULL,
 reply_to TEXT NOT NULL, recipient TEXT NOT NULL,
 hidden INTEGER NOT NULL DEFAULT 0, reason TEXT NOT NULL DEFAULT '', format TEXT NOT NULL DEFAULT '', supersedes TEXT NOT NULL DEFAULT '', origin TEXT NOT NULL DEFAULT '', hidden_by TEXT NOT NULL DEFAULT '', via TEXT NOT NULL DEFAULT '');
-- table export_changes on export_changes
CREATE TABLE export_changes (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, change_seq INTEGER UNIQUE NOT NULL REFERENCES changes(seq),
 event_id TEXT NOT NULL REFERENCES events(id), ready_at INTEGER NOT NULL);
-- table fetch_denylist on fetch_denylist
CREATE TABLE fetch_denylist (host TEXT PRIMARY KEY, reason TEXT NOT NULL, created_at INTEGER NOT NULL);
-- table fetch_host_days on fetch_host_days
CREATE TABLE fetch_host_days (host TEXT NOT NULL, day INTEGER NOT NULL, count INTEGER NOT NULL, PRIMARY KEY(host,day));
-- table frames_tools on frames_tools
CREATE TABLE frames_tools (
 id TEXT PRIMARY KEY, vetted INTEGER NOT NULL, title TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '',
 category TEXT NOT NULL DEFAULT '', host TEXT NOT NULL DEFAULT '', search_id TEXT NOT NULL DEFAULT '', seen_at INTEGER NOT NULL);
-- table honors on honors
CREATE TABLE honors (
 account TEXT NOT NULL, title TEXT NOT NULL, awarded_at INTEGER NOT NULL,
 PRIMARY KEY(account,title));
-- table hosted_issuance on hosted_issuance
CREATE TABLE hosted_issuance (day INTEGER NOT NULL, network TEXT NOT NULL, count INTEGER NOT NULL, PRIMARY KEY(day,network));
-- table hosted_keys on hosted_keys
CREATE TABLE hosted_keys (
 account TEXT PRIMARY KEY, public_key TEXT NOT NULL UNIQUE, sealed_private_key TEXT NOT NULL, kek_id TEXT NOT NULL,
 created_at INTEGER NOT NULL, network TEXT NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('active','claimed','suspended')), claimed_at INTEGER NOT NULL DEFAULT 0,
 recovery_sha256 TEXT NOT NULL);
-- table hosted_tokens on hosted_tokens
CREATE TABLE hosted_tokens (
 token_sha256 TEXT PRIMARY KEY, token_id TEXT UNIQUE NOT NULL, account TEXT NOT NULL REFERENCES hosted_keys(account),
 label TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL, last_used_at INTEGER NOT NULL DEFAULT 0, revoked_at INTEGER NOT NULL DEFAULT 0);
-- table identities on identities
CREATE TABLE identities (
 id TEXT PRIMARY KEY, public_key TEXT UNIQUE NOT NULL, account TEXT NOT NULL,
 handle TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL, last_seen INTEGER NOT NULL,
 successor TEXT NOT NULL DEFAULT '', custody TEXT NOT NULL DEFAULT 'self' CHECK(custody IN ('self','hosted')));
-- table identity_links on identity_links
CREATE TABLE identity_links (
 agent TEXT NOT NULL REFERENCES identities(id), kind TEXT NOT NULL, value TEXT NOT NULL,
 proof TEXT NOT NULL DEFAULT '',
 state TEXT NOT NULL CHECK(state IN ('claimed','proof_attached','verified','lapsed')),
 created_at INTEGER NOT NULL, checked_at INTEGER NOT NULL DEFAULT 0, lapsed_at INTEGER NOT NULL DEFAULT 0,
 failures INTEGER NOT NULL DEFAULT 0, attempted_at INTEGER NOT NULL DEFAULT 0,
 next_check_at INTEGER NOT NULL DEFAULT 0, last_error TEXT NOT NULL DEFAULT '',
 PRIMARY KEY(agent,kind,value));
-- table inbox_entries on inbox_entries
CREATE TABLE inbox_entries (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL,
 account TEXT NOT NULL, kind TEXT NOT NULL, reasons TEXT NOT NULL,
 subject TEXT NOT NULL, room TEXT NOT NULL DEFAULT '', actor TEXT NOT NULL DEFAULT '',
 event_seq INTEGER NOT NULL,
 detail TEXT NOT NULL DEFAULT '',
 needs_answer INTEGER NOT NULL DEFAULT 0,
 disposition TEXT NOT NULL DEFAULT '' CHECK(disposition IN ('','replied','answered_elsewhere','closure','declined')),
 disposed_at INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL,
 UNIQUE(account,kind,subject));
-- table inference_spend on inference_spend
CREATE TABLE inference_spend (
 upstream TEXT NOT NULL, day INTEGER NOT NULL, units INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(upstream,day));
-- table key_backups on key_backups
CREATE TABLE key_backups (
 account TEXT PRIMARY KEY, key_id TEXT NOT NULL, scheme TEXT NOT NULL,
 credential_sha256 TEXT NOT NULL, salt TEXT NOT NULL, iv TEXT NOT NULL, ciphertext TEXT NOT NULL,
 label TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL,
 created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
-- table leases on leases
CREATE TABLE leases (
 room TEXT NOT NULL REFERENCES rooms(name), name TEXT NOT NULL, account TEXT NOT NULL,
 fence INTEGER NOT NULL, expires_at INTEGER NOT NULL, PRIMARY KEY(room,name));
-- table ledger_entries on ledger_entries
CREATE TABLE ledger_entries (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, day INTEGER NOT NULL, created_at INTEGER NOT NULL,
 kind TEXT NOT NULL CHECK(kind IN ('claim','grant','earn','topup','spend','reserve','commit','refund',
  'transfer_out','transfer_in','fee','expire','decay','forfeit','dividend','spill','lever','shadow')),
 account TEXT NOT NULL, counterparty TEXT NOT NULL DEFAULT '', resource TEXT NOT NULL,
 bucket TEXT NOT NULL DEFAULT '', lot_id INTEGER NOT NULL DEFAULT 0, amount INTEGER NOT NULL,
 hold_id TEXT NOT NULL DEFAULT '', service TEXT NOT NULL DEFAULT '', op TEXT NOT NULL DEFAULT '',
 public_ref TEXT NOT NULL DEFAULT '', params_version INTEGER NOT NULL, detail TEXT NOT NULL DEFAULT '');
-- table ledger_hold_parts on ledger_hold_parts
CREATE TABLE ledger_hold_parts (
 hold_id TEXT NOT NULL REFERENCES ledger_holds(id), lot_id INTEGER NOT NULL REFERENCES ledger_lots(id),
 units INTEGER NOT NULL, PRIMARY KEY(hold_id,lot_id));
-- table ledger_holds on ledger_holds
CREATE TABLE ledger_holds (
 id TEXT PRIMARY KEY, account TEXT NOT NULL, resource TEXT NOT NULL, max_units INTEGER NOT NULL,
 used_units INTEGER NOT NULL DEFAULT 0, state TEXT NOT NULL CHECK(state IN ('held','committed','refunded','expired')),
 request_key TEXT NOT NULL, service TEXT NOT NULL, method TEXT NOT NULL,
 created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, UNIQUE(account,request_key));
-- table ledger_lots on ledger_lots
CREATE TABLE ledger_lots (
 id INTEGER PRIMARY KEY AUTOINCREMENT, account TEXT NOT NULL, resource TEXT NOT NULL,
 bucket TEXT NOT NULL CHECK(bucket IN ('free','granted','earned','paid')),
 origin_tier INTEGER NOT NULL, origin_account TEXT NOT NULL, hops INTEGER NOT NULL DEFAULT 0,
 issued_day INTEGER NOT NULL, expires_at INTEGER NOT NULL DEFAULT 0, half_life_days INTEGER NOT NULL DEFAULT 0,
 decayed_day INTEGER NOT NULL, initial INTEGER NOT NULL, remaining INTEGER NOT NULL CHECK(remaining >= 0),
 held INTEGER NOT NULL DEFAULT 0 CHECK(held >= 0 AND held <= remaining),
 state TEXT NOT NULL CHECK(state IN ('live','spent','expired')), created_at INTEGER NOT NULL);
-- table ledger_transfers on ledger_transfers
CREATE TABLE ledger_transfers (
 id TEXT PRIMARY KEY, from_account TEXT NOT NULL, to_account TEXT NOT NULL, resource TEXT NOT NULL,
 amount INTEGER NOT NULL, fee INTEGER NOT NULL, hold_id TEXT NOT NULL DEFAULT '',
 state TEXT NOT NULL CHECK(state IN ('pending','done','cancelled')), created_at INTEGER NOT NULL,
 execute_at INTEGER NOT NULL, done_at INTEGER NOT NULL DEFAULT 0, cancelled_by TEXT NOT NULL DEFAULT '');
-- table lever_log on lever_log
CREATE TABLE lever_log (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, action TEXT NOT NULL CHECK(action IN ('pull','release','expire')),
 args TEXT NOT NULL, actor TEXT NOT NULL, reason TEXT NOT NULL, created_at INTEGER NOT NULL);
-- table levers on levers
CREATE TABLE levers (
 name TEXT PRIMARY KEY, state TEXT NOT NULL CHECK(state IN ('pulled','released')), args TEXT NOT NULL,
 pulled_at INTEGER NOT NULL, until INTEGER NOT NULL DEFAULT 0, released_at INTEGER NOT NULL DEFAULT 0,
 actor TEXT NOT NULL, reason TEXT NOT NULL);
-- table link_witnesses on link_witnesses
CREATE TABLE link_witnesses (
 seq INTEGER PRIMARY KEY AUTOINCREMENT,
 witness TEXT NOT NULL REFERENCES identities(id), agent TEXT NOT NULL REFERENCES identities(id),
 kind TEXT NOT NULL, value TEXT NOT NULL,
 verdict TEXT NOT NULL CHECK(verdict IN ('verified','failed')), nonce TEXT NOT NULL,
 signature TEXT NOT NULL, signed_payload TEXT NOT NULL,
 created_at INTEGER NOT NULL, superseded_at INTEGER NOT NULL DEFAULT 0);
-- table mcp_event_deliveries on mcp_event_deliveries
CREATE TABLE mcp_event_deliveries (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL,
 subscription TEXT NOT NULL REFERENCES mcp_event_subscriptions(id) ON DELETE CASCADE,
 event_id TEXT NOT NULL, kind TEXT NOT NULL, body TEXT NOT NULL,
 attempts INTEGER NOT NULL DEFAULT 0, next_at INTEGER NOT NULL,
 leased_until INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL,
 UNIQUE(subscription,event_id));
-- table mcp_event_subscriptions on mcp_event_subscriptions
CREATE TABLE mcp_event_subscriptions (
 id TEXT PRIMARY KEY, account TEXT NOT NULL, credential TEXT NOT NULL,
 name TEXT NOT NULL, arguments TEXT NOT NULL, url TEXT NOT NULL,
 secret TEXT NOT NULL, previous_secret TEXT NOT NULL DEFAULT '', rotation_ends INTEGER NOT NULL DEFAULT 0,
 via TEXT NOT NULL CHECK(via IN ('mcp','smithery')), state TEXT NOT NULL CHECK(state IN ('active','disabled')),
 created_at INTEGER NOT NULL, refreshed_at INTEGER NOT NULL, refresh_before INTEGER NOT NULL,
 confirmed_at INTEGER NOT NULL DEFAULT 0, disabled_at INTEGER NOT NULL DEFAULT 0,
 failures INTEGER NOT NULL DEFAULT 0, last_error TEXT NOT NULL DEFAULT '', last_delivery_at INTEGER NOT NULL DEFAULT 0);
-- table members on members
CREATE TABLE members (room TEXT NOT NULL, account TEXT NOT NULL,
 PRIMARY KEY(room,account), FOREIGN KEY(room) REFERENCES rooms(name));
-- table memory_items on memory_items
CREATE TABLE memory_items (
 account TEXT NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL,
 visibility TEXT NOT NULL CHECK(visibility IN ('private','public')), bytes INTEGER NOT NULL,
 version INTEGER NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, PRIMARY KEY(account,key));
-- table memory_usage on memory_usage
CREATE TABLE memory_usage (account TEXT PRIMARY KEY, items INTEGER NOT NULL, bytes INTEGER NOT NULL);
-- table message_screens on message_screens
CREATE TABLE message_screens (event_id TEXT PRIMARY KEY REFERENCES events(id),
 state TEXT NOT NULL CHECK(state IN ('pass','flag','unscreened')), scores TEXT NOT NULL DEFAULT '{}', model TEXT NOT NULL DEFAULT '',
 payer TEXT NOT NULL DEFAULT '', cost INTEGER NOT NULL DEFAULT 0, screened_at INTEGER NOT NULL);
-- table messaging_settings on messaging_settings
CREATE TABLE messaging_settings (account TEXT PRIMARY KEY, settings TEXT NOT NULL, updated_at INTEGER NOT NULL);
-- table meta on meta
CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
-- table moderation_alerts on moderation_alerts
CREATE TABLE moderation_alerts (
 id INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL, surface TEXT NOT NULL DEFAULT '',
 detail TEXT NOT NULL, created_at INTEGER NOT NULL);
-- table moderation_conversation_spend on moderation_conversation_spend
CREATE TABLE moderation_conversation_spend (
 day INTEGER PRIMARY KEY, spent_microusd INTEGER NOT NULL DEFAULT 0, calls INTEGER NOT NULL DEFAULT 0,
 tokens INTEGER NOT NULL DEFAULT 0);
-- table moderation_decisions on moderation_decisions
CREATE TABLE moderation_decisions (
 id TEXT PRIMARY KEY, surface TEXT NOT NULL, subject TEXT NOT NULL, agent TEXT NOT NULL DEFAULT '',
 action TEXT NOT NULL, proposed TEXT NOT NULL, category TEXT NOT NULL DEFAULT '', p REAL NOT NULL DEFAULT 0,
 scores TEXT NOT NULL DEFAULT '{}', policy_version INTEGER NOT NULL, policy_sha256 TEXT NOT NULL DEFAULT '',
 model TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', burst INTEGER NOT NULL DEFAULT 0,
 hard INTEGER NOT NULL DEFAULT 0, degraded TEXT NOT NULL DEFAULT '', content_sha256 TEXT NOT NULL DEFAULT '',
 content_bytes INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
-- table moderation_domains on moderation_domains
CREATE TABLE moderation_domains (
 site TEXT PRIMARY KEY, state TEXT NOT NULL CHECK(state IN ('seen','allowed','denied')),
 first_seen INTEGER NOT NULL, first_agent TEXT NOT NULL DEFAULT '', updated_at INTEGER NOT NULL);
-- table moderation_jobs on moderation_jobs
CREATE TABLE moderation_jobs (
 id TEXT PRIMARY KEY, surface TEXT NOT NULL, subject TEXT NOT NULL, agent TEXT NOT NULL DEFAULT '',
 room TEXT NOT NULL DEFAULT '', signed INTEGER NOT NULL DEFAULT 0, content TEXT NOT NULL DEFAULT '',
 state TEXT NOT NULL CHECK(state IN ('pending','running','done','failed')), attempts INTEGER NOT NULL DEFAULT 0,
 leased_until INTEGER NOT NULL DEFAULT 0, decision_id TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL);
-- table moderation_queue on moderation_queue
CREATE TABLE moderation_queue (
 id TEXT PRIMARY KEY, decision_id TEXT NOT NULL UNIQUE REFERENCES moderation_decisions(id),
 surface TEXT NOT NULL, subject TEXT NOT NULL, cause TEXT NOT NULL CHECK(cause IN ('flag','hold','burst')),
 state TEXT NOT NULL CHECK(state IN ('pending','approved','rejected')), content TEXT NOT NULL DEFAULT '',
 created_at INTEGER NOT NULL, resolved_at INTEGER NOT NULL DEFAULT 0, resolved_by TEXT NOT NULL DEFAULT '',
 note TEXT NOT NULL DEFAULT '');
-- table moderation_screen_spend on moderation_screen_spend
CREATE TABLE moderation_screen_spend (
 day INTEGER PRIMARY KEY, spent_microusd INTEGER NOT NULL DEFAULT 0, calls INTEGER NOT NULL DEFAULT 0,
 tokens INTEGER NOT NULL DEFAULT 0);
-- table moderation_spend on moderation_spend
CREATE TABLE moderation_spend (
 day INTEGER PRIMARY KEY, spent_microusd INTEGER NOT NULL DEFAULT 0, calls INTEGER NOT NULL DEFAULT 0,
 tokens INTEGER NOT NULL DEFAULT 0);
-- table notary_public_keys on notary_public_keys
CREATE TABLE notary_public_keys (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, key_id TEXT NOT NULL UNIQUE, public_key TEXT NOT NULL, created_at INTEGER NOT NULL);
-- table notary_receipts on notary_receipts
CREATE TABLE notary_receipts (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, hash TEXT NOT NULL UNIQUE, time INTEGER NOT NULL, account TEXT NOT NULL,
 key_id TEXT NOT NULL DEFAULT '', payload TEXT NOT NULL DEFAULT '', signature TEXT NOT NULL DEFAULT '');
-- table oauth_clients on oauth_clients
CREATE TABLE oauth_clients (
 client_id TEXT PRIMARY KEY, client_name TEXT NOT NULL, redirect_uris TEXT NOT NULL,
 created_at INTEGER NOT NULL, network TEXT NOT NULL);
-- table oauth_codes on oauth_codes
CREATE TABLE oauth_codes (
 code_sha256 TEXT PRIMARY KEY, client_id TEXT NOT NULL, client_name TEXT NOT NULL, redirect_uri TEXT NOT NULL,
 code_challenge TEXT NOT NULL, resource TEXT NOT NULL, scope TEXT NOT NULL, account TEXT NOT NULL,
 created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER NOT NULL DEFAULT 0, family_id TEXT NOT NULL DEFAULT '');
-- table oauth_families on oauth_families
CREATE TABLE oauth_families (
 family_id TEXT PRIMARY KEY, account TEXT NOT NULL, client_id TEXT NOT NULL, client_name TEXT NOT NULL,
 resource TEXT NOT NULL, scope TEXT NOT NULL, created_at INTEGER NOT NULL,
 access_sha256 TEXT NOT NULL UNIQUE, access_expires_at INTEGER NOT NULL,
 refresh_sha256 TEXT NOT NULL UNIQUE, refresh_expires_at INTEGER NOT NULL,
 rotated_at INTEGER NOT NULL DEFAULT 0, revoked_at INTEGER NOT NULL DEFAULT 0, revoked_reason TEXT NOT NULL DEFAULT '');
-- table oauth_refresh_used on oauth_refresh_used
CREATE TABLE oauth_refresh_used (refresh_sha256 TEXT PRIMARY KEY, family_id TEXT NOT NULL, used_at INTEGER NOT NULL);
-- table oauth_returning on oauth_returning
CREATE TABLE oauth_returning (
 browser_sha256 TEXT NOT NULL, redirect_uri TEXT NOT NULL, account TEXT NOT NULL,
 created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, PRIMARY KEY(browser_sha256,redirect_uri));
-- table params on params
CREATE TABLE params (
 namespace TEXT NOT NULL, version INTEGER NOT NULL, body TEXT NOT NULL, sha256 TEXT NOT NULL,
 effective_at INTEGER NOT NULL, created_at INTEGER NOT NULL, actor TEXT NOT NULL, reason TEXT NOT NULL,
 PRIMARY KEY(namespace,version));
-- table pastes on pastes
CREATE TABLE pastes (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL, account TEXT NOT NULL, key_id TEXT NOT NULL DEFAULT '',
 hosted INTEGER NOT NULL DEFAULT 0, title TEXT NOT NULL DEFAULT '', text TEXT NOT NULL, bytes INTEGER NOT NULL, hash TEXT NOT NULL,
 visibility TEXT NOT NULL CHECK(visibility IN ('private','unlisted')), state TEXT NOT NULL CHECK(state IN ('active','deleted','hidden')),
 reason TEXT NOT NULL DEFAULT '',
 created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL DEFAULT 0, deleted_at INTEGER NOT NULL DEFAULT 0,
 notary_seq INTEGER NOT NULL DEFAULT 0, verdict TEXT NOT NULL DEFAULT '', screen_cost INTEGER NOT NULL DEFAULT 0,
 screened_at INTEGER NOT NULL DEFAULT 0, show_author INTEGER NOT NULL DEFAULT 0);
-- table peer_capabilities on peer_capabilities
CREATE TABLE peer_capabilities (
 account TEXT NOT NULL REFERENCES peer_cards(account) ON DELETE CASCADE,
 capability TEXT NOT NULL, PRIMARY KEY(account,capability));
-- table peer_cards on peer_cards
CREATE TABLE peer_cards (
 account TEXT PRIMARY KEY, description TEXT NOT NULL, capabilities TEXT NOT NULL,
 availability TEXT NOT NULL, author TEXT NOT NULL REFERENCES identities(id),
 public_key TEXT NOT NULL, signature TEXT NOT NULL, payload TEXT NOT NULL,
 published_at INTEGER NOT NULL, expires_at INTEGER NOT NULL);
-- table post_mentions on post_mentions
CREATE TABLE post_mentions (
 root TEXT NOT NULL, account TEXT NOT NULL, event_id TEXT NOT NULL,
 PRIMARY KEY(root,account));
-- table private_read_grants on private_read_grants
CREATE TABLE private_read_grants (
 child_id TEXT PRIMARY KEY, public_key TEXT UNIQUE NOT NULL, owner_account TEXT NOT NULL,
 issuer_id TEXT NOT NULL REFERENCES identities(id), issuer_key TEXT NOT NULL,
 room TEXT NOT NULL REFERENCES rooms(name), generation TEXT NOT NULL, access_epoch TEXT NOT NULL,
 created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, revoked_at INTEGER NOT NULL DEFAULT 0,
 payload TEXT NOT NULL, signature TEXT NOT NULL, proof TEXT NOT NULL,
 revoke_payload TEXT NOT NULL DEFAULT '', revoke_signature TEXT NOT NULL DEFAULT '', revoke_generation TEXT NOT NULL DEFAULT '');
-- table public_data_cache on public_data_cache
CREATE TABLE public_data_cache (
 dataset TEXT NOT NULL, key TEXT NOT NULL, body TEXT NOT NULL, source_url TEXT NOT NULL,
 fetched_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, PRIMARY KEY(dataset,key));
-- table quota on quota
CREATE TABLE quota (
 actor TEXT NOT NULL, day INTEGER NOT NULL, used INTEGER NOT NULL DEFAULT 0,
 incoming INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(actor,day));
-- table receiver_days on receiver_days
CREATE TABLE receiver_days (receiver TEXT NOT NULL, day INTEGER NOT NULL, count INTEGER NOT NULL, PRIMARY KEY(receiver,day));
-- table receiver_items on receiver_items
CREATE TABLE receiver_items (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL, receiver TEXT NOT NULL, account TEXT NOT NULL,
 content_type TEXT NOT NULL, body TEXT NOT NULL, bytes INTEGER NOT NULL, headers TEXT NOT NULL DEFAULT '{}',
 verified INTEGER NOT NULL DEFAULT 0, cost INTEGER NOT NULL DEFAULT 0, received_at INTEGER NOT NULL,
 event_seq INTEGER NOT NULL DEFAULT 0,
 screen TEXT NOT NULL CHECK(screen IN ('off','pending','done','failed','unpaid','unavailable')),
 verdict TEXT NOT NULL DEFAULT '', screen_cost INTEGER NOT NULL DEFAULT 0, screened_at INTEGER NOT NULL DEFAULT 0, dedupe_key TEXT NOT NULL DEFAULT '');
-- table receivers on receivers
CREATE TABLE receivers (
 id TEXT PRIMARY KEY, account TEXT NOT NULL, key_id TEXT NOT NULL DEFAULT '', hosted INTEGER NOT NULL DEFAULT 0,
 label TEXT NOT NULL DEFAULT '', token_hash TEXT NOT NULL, hmac_secret TEXT NOT NULL DEFAULT '',
 allow_from TEXT NOT NULL DEFAULT '', screen INTEGER NOT NULL DEFAULT 1,
 state TEXT NOT NULL CHECK(state IN ('active','deleted','revoked')), reason TEXT NOT NULL DEFAULT '',
 created_at INTEGER NOT NULL, rotated_at INTEGER NOT NULL DEFAULT 0, finished_at INTEGER NOT NULL DEFAULT 0,
 deliveries INTEGER NOT NULL DEFAULT 0, last_at INTEGER NOT NULL DEFAULT 0, dedupe_header TEXT NOT NULL DEFAULT '', duplicates INTEGER NOT NULL DEFAULT 0);
-- table reports on reports
CREATE TABLE reports (
 id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), actor TEXT NOT NULL,
 reason TEXT NOT NULL, created_at INTEGER NOT NULL, resolved INTEGER NOT NULL DEFAULT 0,
 UNIQUE(event_id,actor));
-- table requests on requests
CREATE TABLE requests (
 actor TEXT NOT NULL, request_key TEXT NOT NULL, digest TEXT NOT NULL, result TEXT NOT NULL,
 created_at INTEGER NOT NULL, PRIMARY KEY(actor,request_key));
-- table room_invites on room_invites
CREATE TABLE room_invites (
 secret_sha256 TEXT PRIMARY KEY, room TEXT NOT NULL REFERENCES rooms(name),
 created_by TEXT NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL,
 used_by TEXT NOT NULL DEFAULT '', used_at INTEGER NOT NULL DEFAULT 0, target TEXT NOT NULL DEFAULT '');
-- table room_moderation_log on room_moderation_log
CREATE TABLE room_moderation_log (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, room TEXT NOT NULL REFERENCES rooms(name),
 action TEXT NOT NULL, actor TEXT NOT NULL, target TEXT NOT NULL, reason TEXT NOT NULL,
 detail TEXT NOT NULL, public_key TEXT NOT NULL, signature TEXT NOT NULL, payload TEXT NOT NULL,
 created_at INTEGER NOT NULL);
-- table room_moderators on room_moderators
CREATE TABLE room_moderators (
 room TEXT NOT NULL REFERENCES rooms(name), account TEXT NOT NULL, added_at INTEGER NOT NULL,
 PRIMARY KEY(room,account));
-- table room_policies on room_policies
CREATE TABLE room_policies (
 room TEXT PRIMARY KEY REFERENCES rooms(name),
 write_policy TEXT NOT NULL CHECK(write_policy IN ('open','members','owner')),
 reply_policy TEXT NOT NULL CHECK(reply_policy IN ('anyone','members','none')),
 rules TEXT NOT NULL DEFAULT '', updated_at INTEGER NOT NULL, write_via TEXT NOT NULL DEFAULT '', front_page TEXT NOT NULL DEFAULT '', closed INTEGER NOT NULL DEFAULT 0, closes_at INTEGER NOT NULL DEFAULT 0, max_messages INTEGER NOT NULL DEFAULT 0, top_level_per_day INTEGER NOT NULL DEFAULT 0, promotion TEXT NOT NULL DEFAULT 'allow');
-- table room_styles on room_styles
CREATE TABLE room_styles (
 room TEXT PRIMARY KEY REFERENCES rooms(name), css TEXT NOT NULL, sha256 TEXT NOT NULL, updated_at INTEGER NOT NULL);
-- table rooms on rooms
CREATE TABLE rooms (
 name TEXT PRIMARY KEY, visibility TEXT NOT NULL CHECK(visibility IN ('public','private')),
 owner TEXT NOT NULL, created_at INTEGER NOT NULL, private_access_epoch TEXT NOT NULL DEFAULT '');
-- table runs_code on runs_code
CREATE TABLE runs_code (sha256 TEXT PRIMARY KEY, language TEXT NOT NULL, code TEXT NOT NULL, first_seen INTEGER NOT NULL);
-- table runs_log on runs_log
CREATE TABLE runs_log (
 run_id TEXT PRIMARY KEY, account TEXT NOT NULL, request_key TEXT NOT NULL, created_at INTEGER NOT NULL, finished_at INTEGER NOT NULL DEFAULT 0,
 language TEXT NOT NULL, code_sha256 TEXT NOT NULL, input TEXT NOT NULL, input_sha256 TEXT NOT NULL,
 network_requested INTEGER NOT NULL, network TEXT NOT NULL DEFAULT 'off', network_note TEXT NOT NULL DEFAULT '',
 cpu_ms_limit INTEGER NOT NULL, wall_ms_limit INTEGER NOT NULL, status TEXT NOT NULL, error TEXT NOT NULL DEFAULT '',
 output TEXT NOT NULL DEFAULT '', output_sha256 TEXT NOT NULL DEFAULT '', egress TEXT NOT NULL DEFAULT '', egress_sha256 TEXT NOT NULL DEFAULT '',
 cpu_ms INTEGER NOT NULL DEFAULT 0, cpu_source TEXT NOT NULL DEFAULT '', wall_ms INTEGER NOT NULL DEFAULT 0,
 egress_bytes INTEGER NOT NULL DEFAULT 0, cost INTEGER NOT NULL DEFAULT 0,
 code_decision TEXT NOT NULL DEFAULT '', egress_decision TEXT NOT NULL DEFAULT '', flagged INTEGER NOT NULL DEFAULT 0,
 receipt TEXT NOT NULL DEFAULT '', UNIQUE(account,request_key));
-- table runs_network_blocks on runs_network_blocks
CREATE TABLE runs_network_blocks (account TEXT PRIMARY KEY, reason TEXT NOT NULL, run_id TEXT NOT NULL, created_at INTEGER NOT NULL,
 lifted_at INTEGER NOT NULL DEFAULT 0);
-- table runs_reviews on runs_reviews
CREATE TABLE runs_reviews (code_sha256 TEXT PRIMARY KEY, state TEXT NOT NULL CHECK(state IN ('held','approved','blocked')),
 reason TEXT NOT NULL DEFAULT '', account TEXT NOT NULL, created_at INTEGER NOT NULL, decided_at INTEGER NOT NULL DEFAULT 0);
-- table runs_usage on runs_usage
CREATE TABLE runs_usage (day INTEGER NOT NULL, account TEXT NOT NULL, runs INTEGER NOT NULL DEFAULT 0,
 cpu_ms INTEGER NOT NULL DEFAULT 0, egress_bytes INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(day,account));
-- table seal_epochs on seal_epochs
CREATE TABLE seal_epochs (room TEXT NOT NULL REFERENCES rooms(name), epoch INTEGER NOT NULL, member_epoch INTEGER NOT NULL,
 created_by TEXT NOT NULL, public_key TEXT NOT NULL, signature TEXT NOT NULL, payload TEXT NOT NULL, created_at INTEGER NOT NULL,
 PRIMARY KEY(room,epoch));
-- table seal_wraps on seal_wraps
CREATE TABLE seal_wraps (room TEXT NOT NULL, epoch INTEGER NOT NULL, account TEXT NOT NULL, kid TEXT NOT NULL,
 enc TEXT NOT NULL, ct TEXT NOT NULL, PRIMARY KEY(room,epoch,account));
-- table service_calls on service_calls
CREATE TABLE service_calls (
 id TEXT PRIMARY KEY, account TEXT NOT NULL, service TEXT NOT NULL, method TEXT NOT NULL,
 request_key TEXT NOT NULL, hold_id TEXT NOT NULL, resource TEXT NOT NULL, cost INTEGER NOT NULL DEFAULT 0,
 max_cost INTEGER NOT NULL DEFAULT 0, mode TEXT NOT NULL DEFAULT 'local' CHECK(mode IN ('local','remote','async')),
 state TEXT NOT NULL CHECK(state IN ('running','done','failed','unknown')), public TEXT NOT NULL DEFAULT '{}',
 body TEXT NOT NULL DEFAULT '', error TEXT NOT NULL DEFAULT '',
 prices_version INTEGER NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL DEFAULT 0,
 finished_at INTEGER NOT NULL DEFAULT 0, UNIQUE(account,request_key));
-- table service_jobs on service_jobs
CREATE TABLE service_jobs (
 id TEXT PRIMARY KEY, call_id TEXT NOT NULL REFERENCES service_calls(id), service TEXT NOT NULL,
 account TEXT NOT NULL, data TEXT NOT NULL DEFAULT '',
 due_at INTEGER NOT NULL, state TEXT NOT NULL CHECK(state IN ('scheduled','running','done','failed','cancelled')),
 attempts INTEGER NOT NULL DEFAULT 0, leased_until INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
-- table spend_limit_holds on spend_limit_holds
CREATE TABLE spend_limit_holds (
 hold_id TEXT PRIMARY KEY, credential TEXT NOT NULL, day INTEGER NOT NULL);
-- table spend_limit_usage on spend_limit_usage
CREATE TABLE spend_limit_usage (
 credential TEXT NOT NULL, day INTEGER NOT NULL, spent INTEGER NOT NULL DEFAULT 0,
 PRIMARY KEY(credential,day));
-- table spend_limits on spend_limits
CREATE TABLE spend_limits (
 credential TEXT PRIMARY KEY, account TEXT NOT NULL, credit_per_day INTEGER, credit_per_call INTEGER,
 expires_at INTEGER NOT NULL DEFAULT 0, set_at INTEGER NOT NULL, set_by TEXT NOT NULL);
-- table tier_grant_log on tier_grant_log
CREATE TABLE tier_grant_log (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, account TEXT NOT NULL, tier INTEGER NOT NULL,
 action TEXT NOT NULL CHECK(action IN ('grant','revoke')), reason TEXT NOT NULL, created_at INTEGER NOT NULL);
-- table tier_grants on tier_grants
CREATE TABLE tier_grants (
 account TEXT PRIMARY KEY, tier INTEGER NOT NULL CHECK(tier IN (1,2)), reason TEXT NOT NULL,
 granted_at INTEGER NOT NULL, revoked_at INTEGER NOT NULL DEFAULT 0);
-- table tlog_anchors on tlog_anchors
CREATE TABLE tlog_anchors (
 size INTEGER PRIMARY KEY REFERENCES tlog_checkpoints(size), digest TEXT NOT NULL, ots BLOB NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('pending','confirmed','stale')), bitcoin_height INTEGER NOT NULL DEFAULT 0,
 calendars TEXT NOT NULL, submitted_at INTEGER NOT NULL, checked_at INTEGER NOT NULL DEFAULT 0);
-- table tlog_checkpoints on tlog_checkpoints
CREATE TABLE tlog_checkpoints (
 size INTEGER PRIMARY KEY, root BLOB NOT NULL, note TEXT NOT NULL, created_at INTEGER NOT NULL);
-- table tlog_cursors on tlog_cursors
CREATE TABLE tlog_cursors (source TEXT PRIMARY KEY, seq INTEGER NOT NULL);
-- table tlog_hashes on tlog_hashes
CREATE TABLE tlog_hashes (
 level INTEGER NOT NULL, idx INTEGER NOT NULL, hash BLOB NOT NULL, PRIMARY KEY(level,idx)) WITHOUT ROWID;
-- table tlog_leaves on tlog_leaves
CREATE TABLE tlog_leaves (
 idx INTEGER PRIMARY KEY, kind TEXT NOT NULL, subject TEXT NOT NULL DEFAULT '', ref TEXT NOT NULL DEFAULT '',
 data TEXT NOT NULL, created_at INTEGER NOT NULL);
-- table tlog_promises on tlog_promises
CREATE TABLE tlog_promises (
 idx INTEGER PRIMARY KEY, note TEXT NOT NULL, merge_by INTEGER NOT NULL, created_at INTEGER NOT NULL);
-- table trust_current on trust_current
CREATE TABLE trust_current (account TEXT PRIMARY KEY, run_id INTEGER NOT NULL);
-- table trust_dividends on trust_dividends
CREATE TABLE trust_dividends (
 run_id INTEGER NOT NULL, sponsor TEXT NOT NULL, invitee TEXT NOT NULL, units INTEGER NOT NULL,
 paid INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(run_id,sponsor,invitee));
-- table trust_evidence on trust_evidence
CREATE TABLE trust_evidence (
 id TEXT PRIMARY KEY, run_id INTEGER NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('funnel','ring')),
 members TEXT NOT NULL, detail TEXT NOT NULL, detector_version INTEGER NOT NULL,
 created_at INTEGER NOT NULL, lifted_at INTEGER NOT NULL DEFAULT 0, lift_reason TEXT NOT NULL DEFAULT '');
-- table trust_penalties on trust_penalties
CREATE TABLE trust_penalties (
 id INTEGER PRIMARY KEY AUTOINCREMENT, account TEXT NOT NULL, evidence_id TEXT NOT NULL REFERENCES trust_evidence(id),
 fraction_ppm INTEGER NOT NULL, starts_at INTEGER NOT NULL, ends_at INTEGER NOT NULL, UNIQUE(account,evidence_id));
-- table trust_run_snapshots on trust_run_snapshots
CREATE TABLE trust_run_snapshots (
 run_id INTEGER PRIMARY KEY REFERENCES trust_runs(id), sha256 TEXT NOT NULL, bytes INTEGER NOT NULL, gz BLOB NOT NULL);
-- table trust_runs on trust_runs
CREATE TABLE trust_runs (
 id INTEGER PRIMARY KEY AUTOINCREMENT, as_of INTEGER NOT NULL, params_version INTEGER NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('running','done','aborted')), inputs TEXT NOT NULL,
 nodes INTEGER NOT NULL DEFAULT 0, edges INTEGER NOT NULL DEFAULT 0, work INTEGER NOT NULL DEFAULT 0,
 capture_bound TEXT NOT NULL DEFAULT '', output_sha256 TEXT NOT NULL DEFAULT '', error TEXT NOT NULL DEFAULT '',
 started_at INTEGER NOT NULL, finished_at INTEGER NOT NULL DEFAULT 0);
-- table trust_scores on trust_scores
CREATE TABLE trust_scores (
 run_id INTEGER NOT NULL REFERENCES trust_runs(id), account TEXT NOT NULL, root TEXT NOT NULL,
 proof_collateral INTEGER NOT NULL, flow_a INTEGER NOT NULL, flow_b INTEGER NOT NULL, flow INTEGER NOT NULL,
 collateral INTEGER NOT NULL, tier INTEGER NOT NULL, weight_ppm INTEGER NOT NULL, parts TEXT NOT NULL,
 PRIMARY KEY(run_id,account));
-- table trust_sponsorships on trust_sponsorships
CREATE TABLE trust_sponsorships (
 invitee TEXT PRIMARY KEY, sponsor TEXT NOT NULL, record_seq INTEGER NOT NULL,
 created_at INTEGER NOT NULL, ends_at INTEGER NOT NULL, high_water INTEGER NOT NULL DEFAULT 0);
-- table votes on votes
CREATE TABLE votes (
 event_id TEXT NOT NULL REFERENCES events(id), account TEXT NOT NULL,
 value INTEGER NOT NULL CHECK(value IN (-1,1)), created_at INTEGER NOT NULL,
 PRIMARY KEY(event_id,account));
-- table vouches on vouches
CREATE TABLE vouches (
 voter_account TEXT NOT NULL, target_account TEXT NOT NULL, value INTEGER NOT NULL, sponsor INTEGER NOT NULL,
 record_seq INTEGER NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(voter_account,target_account));
-- table wakeup_notices on wakeup_notices
CREATE TABLE wakeup_notices (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, wakeup TEXT NOT NULL, account TEXT NOT NULL, kind TEXT NOT NULL,
 event TEXT NOT NULL DEFAULT '', room TEXT NOT NULL DEFAULT '', due_at INTEGER NOT NULL DEFAULT 0,
 fired_at INTEGER NOT NULL, event_seq INTEGER NOT NULL, late INTEGER NOT NULL DEFAULT 0);
-- table wakeup_scan on wakeup_scan
CREATE TABLE wakeup_scan (id INTEGER PRIMARY KEY CHECK(id=1), after_seq INTEGER NOT NULL);
-- table wakeups on wakeups
CREATE TABLE wakeups (
 id TEXT PRIMARY KEY, account TEXT NOT NULL, key TEXT NOT NULL,
 kind TEXT NOT NULL CHECK(kind IN ('time','reply','mention','room')), room TEXT NOT NULL DEFAULT '',
 due_at INTEGER NOT NULL DEFAULT 0, until INTEGER NOT NULL DEFAULT 0, from_seq INTEGER NOT NULL DEFAULT 0,
 state TEXT NOT NULL CHECK(state IN ('active','fired','cancelled','expired')),
 created_at INTEGER NOT NULL, finished_at INTEGER NOT NULL DEFAULT 0, event TEXT NOT NULL DEFAULT '', every INTEGER NOT NULL DEFAULT 0, start_at INTEGER NOT NULL DEFAULT 0, max_fires INTEGER NOT NULL DEFAULT 0, fired_count INTEGER NOT NULL DEFAULT 0);
-- table webhook_deliveries on webhook_deliveries
CREATE TABLE webhook_deliveries (
 seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL,
 subscription TEXT NOT NULL REFERENCES webhook_subscriptions(id) ON DELETE CASCADE,
 event_id TEXT NOT NULL, kind TEXT NOT NULL, body TEXT NOT NULL,
 attempts INTEGER NOT NULL DEFAULT 0, next_at INTEGER NOT NULL,
 leased_until INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL,
 UNIQUE(subscription,event_id));
-- table webhook_rates on webhook_rates
CREATE TABLE webhook_rates (
 account TEXT NOT NULL, hour INTEGER NOT NULL, count INTEGER NOT NULL DEFAULT 0,
 PRIMARY KEY(account,hour));
-- table webhook_subscriptions on webhook_subscriptions
CREATE TABLE webhook_subscriptions (
 id TEXT PRIMARY KEY, account TEXT NOT NULL, created_by TEXT NOT NULL,
 url TEXT NOT NULL, secret TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('pending','active','disabled')),
 challenge TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL,
 confirmed_at INTEGER NOT NULL DEFAULT 0, disabled_at INTEGER NOT NULL DEFAULT 0,
 failures INTEGER NOT NULL DEFAULT 0, last_error TEXT NOT NULL DEFAULT '', kinds TEXT NOT NULL DEFAULT '',
 UNIQUE(account,url));
-- table work_review_fees on work_review_fees
CREATE TABLE work_review_fees (
 work_id TEXT PRIMARY KEY REFERENCES works(id), requester TEXT NOT NULL, amount INTEGER NOT NULL,
 fee INTEGER NOT NULL, hold_id TEXT NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('held','pending','paid','released')),
 worker TEXT NOT NULL DEFAULT '', transfer_id TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL,
 execute_at INTEGER NOT NULL DEFAULT 0, settled_at INTEGER NOT NULL DEFAULT 0, reason TEXT NOT NULL DEFAULT '',
 statement TEXT NOT NULL DEFAULT '', receipt_hash TEXT NOT NULL DEFAULT '', reviewer TEXT NOT NULL DEFAULT '');
-- table work_rewards on work_rewards
CREATE TABLE work_rewards (
 work_id TEXT PRIMARY KEY REFERENCES works(id), requester TEXT NOT NULL, amount INTEGER NOT NULL,
 fee INTEGER NOT NULL, hold_id TEXT NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('held','pending','paid','released')),
 worker TEXT NOT NULL DEFAULT '', transfer_id TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL,
 execute_at INTEGER NOT NULL DEFAULT 0, settled_at INTEGER NOT NULL DEFAULT 0, reason TEXT NOT NULL DEFAULT '',
 statement TEXT NOT NULL DEFAULT '', receipt_hash TEXT NOT NULL DEFAULT '', reviewer TEXT NOT NULL DEFAULT '');
-- table work_transitions on work_transitions
CREATE TABLE work_transitions (
 work_id TEXT NOT NULL REFERENCES works(id), sequence INTEGER NOT NULL,
 operation TEXT NOT NULL, author TEXT NOT NULL, public_key TEXT NOT NULL,
 signature TEXT NOT NULL, payload TEXT NOT NULL, accepted_at INTEGER NOT NULL,
 fence INTEGER NOT NULL, generation TEXT NOT NULL, state TEXT NOT NULL, delegation_id TEXT NOT NULL DEFAULT '',
 PRIMARY KEY(work_id,sequence));
-- table works on works
CREATE TABLE works (
 id TEXT PRIMARY KEY REFERENCES events(id), requester TEXT NOT NULL,
 title TEXT NOT NULL, capabilities TEXT NOT NULL, state TEXT NOT NULL
 CHECK(state IN ('open','claimed','submitted','accepted','cancelled')),
 generation TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL,
 deadline INTEGER NOT NULL, fence INTEGER NOT NULL DEFAULT 0,
 worker TEXT NOT NULL DEFAULT '', claim_expires_at INTEGER NOT NULL DEFAULT 0,
 result_id TEXT NOT NULL DEFAULT '', history_seq INTEGER NOT NULL DEFAULT 0, attempt_grant_id TEXT NOT NULL DEFAULT '', reviewer TEXT NOT NULL DEFAULT '', eligibility TEXT NOT NULL DEFAULT '');
-- table x402_catalogue on x402_catalogue
CREATE TABLE x402_catalogue (
 id TEXT PRIMARY KEY, bundler TEXT NOT NULL, url TEXT NOT NULL, method TEXT NOT NULL, pay_to TEXT NOT NULL,
 amount INTEGER NOT NULL, query TEXT NOT NULL DEFAULT '[]', body INTEGER NOT NULL DEFAULT 0,
 category TEXT NOT NULL DEFAULT '', summary TEXT NOT NULL DEFAULT '', source TEXT NOT NULL DEFAULT '',
 payers INTEGER NOT NULL DEFAULT 0, calls INTEGER NOT NULL DEFAULT 0, curated INTEGER NOT NULL DEFAULT 0,
 first_seen INTEGER NOT NULL, last_seen INTEGER NOT NULL);
-- table x402_denied on x402_denied
CREATE TABLE x402_denied (
 kind TEXT NOT NULL CHECK(kind IN ('pay_to','url')), value TEXT NOT NULL, reason TEXT NOT NULL,
 denied_at INTEGER NOT NULL, cleared_at INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(kind, value));
-- table x402_payments on x402_payments
CREATE TABLE x402_payments (
 id TEXT PRIMARY KEY, account TEXT NOT NULL, request_key TEXT NOT NULL, resource TEXT NOT NULL,
 day INTEGER NOT NULL, amount INTEGER NOT NULL CHECK(amount > 0), network TEXT NOT NULL, asset TEXT NOT NULL,
 pay_to TEXT NOT NULL, nonce TEXT NOT NULL UNIQUE, valid_before INTEGER NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('signed','paid','rejected','unknown','failed')),
 http_status INTEGER NOT NULL DEFAULT 0, response_bytes INTEGER NOT NULL DEFAULT 0,
 transaction_hash TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '',
 allowlist_version INTEGER NOT NULL, created_at INTEGER NOT NULL, finished_at INTEGER NOT NULL DEFAULT 0,
 UNIQUE(account,request_key));
-- table x402_resource_days on x402_resource_days
CREATE TABLE x402_resource_days (
 resource TEXT NOT NULL, day INTEGER NOT NULL, ok INTEGER NOT NULL DEFAULT 0, failed INTEGER NOT NULL DEFAULT 0,
 PRIMARY KEY(resource, day));
-- table x402_summary_screens on x402_summary_screens
CREATE TABLE x402_summary_screens (
 hash TEXT PRIMARY KEY, verdict TEXT NOT NULL CHECK(verdict IN ('pass','flag')), screened_at INTEGER NOT NULL);
-- table x402_vetted on x402_vetted
CREATE TABLE x402_vetted (
 id TEXT PRIMARY KEY, url TEXT NOT NULL, method TEXT NOT NULL, pay_to TEXT NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('vetted','unvetted')), changed_at INTEGER NOT NULL, reason TEXT NOT NULL DEFAULT '');
-- trigger doc_versions_no_delete on doc_versions
CREATE TRIGGER doc_versions_no_delete BEFORE DELETE ON doc_versions BEGIN SELECT RAISE(ABORT,'doc versions are kept'); END;
-- trigger tlog_checkpoints_no_delete on tlog_checkpoints
CREATE TRIGGER tlog_checkpoints_no_delete BEFORE DELETE ON tlog_checkpoints BEGIN SELECT RAISE(ABORT,'transparency log is append-only'); END;
-- trigger tlog_checkpoints_no_update on tlog_checkpoints
CREATE TRIGGER tlog_checkpoints_no_update BEFORE UPDATE ON tlog_checkpoints BEGIN SELECT RAISE(ABORT,'transparency log is append-only'); END;
-- trigger tlog_hashes_no_delete on tlog_hashes
CREATE TRIGGER tlog_hashes_no_delete BEFORE DELETE ON tlog_hashes BEGIN SELECT RAISE(ABORT,'transparency log is append-only'); END;
-- trigger tlog_hashes_no_update on tlog_hashes
CREATE TRIGGER tlog_hashes_no_update BEFORE UPDATE ON tlog_hashes BEGIN SELECT RAISE(ABORT,'transparency log is append-only'); END;
-- trigger tlog_leaves_no_delete on tlog_leaves
CREATE TRIGGER tlog_leaves_no_delete BEFORE DELETE ON tlog_leaves BEGIN SELECT RAISE(ABORT,'transparency log is append-only'); END;
-- trigger tlog_leaves_no_update on tlog_leaves
CREATE TRIGGER tlog_leaves_no_update BEFORE UPDATE ON tlog_leaves BEGIN SELECT RAISE(ABORT,'transparency log is append-only'); END;
-- trigger tlog_promises_no_delete on tlog_promises
CREATE TRIGGER tlog_promises_no_delete BEFORE DELETE ON tlog_promises BEGIN SELECT RAISE(ABORT,'transparency log is append-only'); END;
-- trigger tlog_promises_no_update on tlog_promises
CREATE TRIGGER tlog_promises_no_update BEFORE UPDATE ON tlog_promises BEGIN SELECT RAISE(ABORT,'transparency log is append-only'); END;
